
' PLC values not handled by onboard memory
Global Long PLC_Delay_BlowOffTime
Global Long PLC_Delay_InsertLoad
Global Long PLC_Speed_TorqueMode
Global Long PLC_Torque_TorqueMode
Global Long PLC_Delay_RejectBlowOff
Global Long PLC_Delay_FindHome
Global Long PLC_Delay_ActiveCooling
Global Long PLC_Delay_TorqueDwell
Global Long PLC_Delay_Gripper
Global Long PLC_Delay_PanelContact
Global Long PLC_Delay_ShuttleExtended
Global Long PLC_InsertType
Global Long PLC_PanelContactTorque
Global Long PLC_InsertTempOkBand
Global Long PLC_PID_SetValue
Global Long PLC_PID_ProcessValue
Global Long PLC_ServoMotorCurrentValue

