
' Recipe Ingredients for Panels
Global Integer recNumberOfHoles, recInsertType, recInmag, recOutmag, recCrowding, recPreCrowding
Global Double recPartNumber
Global Boolean recFlashRequired, recPopPanelRequired, recPreinspectionRequired, recCrowdingRequired
Global Boolean recHotStakePanelRequired, recInspectionRequired, recPushPanelRequired
Global Real recInsertDepth, recHeatStakeOffset
Global Real recTempProbe, recTempTrack, recBossCrossArea, recSuctionWaitTime
Global Integer recFirstHolePointInspection, recLastHolePointInspection
Global Integer recFirstHolePointHotStake, recLastHolePointHotStake, recPointsTable
Global Integer recFirstHolePointFlash, recLastHolePointFlash
Global Real recFlashDwellTime ' How long the flash tool is in contact with the insert



