
' Recipe Ingredients for Panels
Global Integer recNumberOfHoles, recInsertType
Global Boolean recFlashRequired, recPopPanelRequired, recPreinspectionRequired, recCrowdingRequired
Global Boolean recHotStakePanelRequired, recInspectionRequired, recPushPanelRequired
Global Real recInsertDepth
Global Real recBossCrossArea, recSuctionWaitTime
Global Real recFlashDwellTime ' How long the flash tool is in contact with the insert



